
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Alexander
 */
public class FenetreQuiz extends javax.swing.JFrame {

    private int score = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    ArrayList<Question> Questions = new ArrayList<Question>();
    private int indexQuestionCourante = 0;

    /**
     * Creates new form FenetreQuiz
     */
    private void afficherQuestionCourante() {
        Question q = Questions.get(indexQuestionCourante);
        lblQuestion.setText(q.getIntitule());
        btnRep1.setText(q.getProposition1());
        btnRep2.setText(q.getProposition2());
        btnRep3.setText(q.getProposition3());
        btnRep4.setText(q.getProposition4());
        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);

    }

    public FenetreQuiz() {
        initComponents();

        Questions.add(new Question("Capital de la France ?", "Paris", "Londres", "Berlin", "Rome", 1));
        Questions.add(new Question("2 + 2 = ?", "3", "4", "5", "6", 2));
        Questions.add(new Question("Langage pour Android ?", "Java", "Python", "C#", "Swift", 1));
        Questions.add(new Question("Couleur du ciel ?", "Bleu", "Vert", "Rouge", "Jaune", 1));
        Questions.add(new Question("Résultat de 5 * 3 ?", "10", "15", "20", "25", 2));

        afficherQuestionCourante(); // Affiche la première question
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        lblFeedBack = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setText("lblQuestion");

        btnRep1.setText("Réponse 1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("Réponse 2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("Réponse 3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("Réponse 4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        btnSuivant.setText("Next");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        lblFeedBack.setText("Feedback");

        lblScore.setText("Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnRep1)
                        .addGap(18, 18, 18)
                        .addComponent(btnRep2)
                        .addGap(18, 18, 18)
                        .addComponent(btnRep3)
                        .addGap(18, 18, 18)
                        .addComponent(btnRep4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lblQuestion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblFeedBack)
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblScore)
                            .addComponent(btnSuivant))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblQuestion)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep1)
                    .addComponent(btnRep2)
                    .addComponent(btnRep3)
                    .addComponent(btnRep4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFeedBack)
                    .addComponent(lblScore))
                .addGap(19, 19, 19)
                .addComponent(btnSuivant)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed

        int val1 = 1;
        Question q = Questions.get(indexQuestionCourante);

        if (val1 == q.getIndexBonneReponse()) {
            lblFeedBack.setText("Bonne réponse");
            score++;
            lblScore.setText("Votre score est : " + score);
        } else {
            lblFeedBack.setText("Mauvaise réponse");
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        int val2 = 2;
        Question q = Questions.get(indexQuestionCourante);

        if (val2 == q.getIndexBonneReponse()) {
            lblFeedBack.setText("Bonne réponse");
            score++;
            lblScore.setText("Votre score est : " + score);
        } else {
            lblFeedBack.setText("Mauvaise réponse");
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        int val3 = 3;
        Question q = Questions.get(indexQuestionCourante);

        if (val3 == q.getIndexBonneReponse()) {
            lblFeedBack.setText("Bonne réponse");
            score++;
            lblScore.setText("Votre score est : " + score);
        } else {
            lblFeedBack.setText("Mauvaise réponse");
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        int val4 = 4;
        Question q = Questions.get(indexQuestionCourante);

        if (val4 == q.getIndexBonneReponse()) {
            lblFeedBack.setText("Bonne réponse");
            score++;
            lblScore.setText("Votre score est : " + score);
        } else {
            lblFeedBack.setText("Mauvaise réponse");
        }

        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        indexQuestionCourante++;
        if (indexQuestionCourante < Questions.size()) {
            afficherQuestionCourante();
            lblFeedBack.setText(""); 
        } else {
            lblFeedBack.setText("Quiz terminé. Score : " + score + " / " + Questions.size());
            btnSuivant.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnSuivantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JLabel lblFeedBack;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables
}


//Jusqu'à l'étape 6 inclu
