/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexander
 */
public class ecran_defaite extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ecran_defaite.class.getName());

    /**
     * Creates new form ecran_defaite
     */
    public ecran_defaite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Defaite_label = new javax.swing.JLabel();
        EcranTitre_bouton = new javax.swing.JButton();
        Relancer_bouton = new javax.swing.JButton();
        Quitter_défaite_bouton = new javax.swing.JButton();
        image_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Defaite_label.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        Defaite_label.setText("Défaite");

        EcranTitre_bouton.setText("Retour à l'écran titre");
        EcranTitre_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcranTitre_boutonActionPerformed(evt);
            }
        });

        Relancer_bouton.setText("Recommencer");
        Relancer_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Relancer_boutonActionPerformed(evt);
            }
        });

        Quitter_défaite_bouton.setText("Quitter");
        Quitter_défaite_bouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quitter_défaite_boutonActionPerformed(evt);
            }
        });

        image_label.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(EcranTitre_bouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(Relancer_bouton)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(image_label)
                        .addGap(45, 45, 45)
                        .addComponent(Defaite_label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(Quitter_défaite_bouton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Defaite_label, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image_label))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EcranTitre_bouton)
                    .addComponent(Relancer_bouton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Quitter_défaite_bouton)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EcranTitre_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcranTitre_boutonActionPerformed
        // TODO add your handling code here:
        ecran_titre accueil = new ecran_titre();
        accueil.setLocationRelativeTo(this); 
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EcranTitre_boutonActionPerformed

    private void Relancer_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Relancer_boutonActionPerformed
        // TODO add your handling code here:
        Interface jeu = new Interface();
        jeu.setTitle("Cadenas - Partie");
        jeu.setLocationRelativeTo(null);
        jeu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Relancer_boutonActionPerformed

    private void Quitter_défaite_boutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quitter_défaite_boutonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_Quitter_défaite_boutonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ecran_defaite().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Defaite_label;
    private javax.swing.JButton EcranTitre_bouton;
    private javax.swing.JButton Quitter_défaite_bouton;
    private javax.swing.JButton Relancer_bouton;
    private javax.swing.JLabel image_label;
    // End of variables declaration//GEN-END:variables
}
