/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alexander
 */
public class Interface extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());
        Cadenas Solution = new Cadenas(1,2,3,4);
        Cadenas now = new Cadenas(0,0,0,0);
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres__haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouver le bon code en moins de 5 tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 40, -1, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 40, -1, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 40, -1, -1));

                        texte_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_1.setText("0");
                        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        texte_chiffre_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 30, -1));

                        texte_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_2.setText("0");
                        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        texte_chiffre_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

                        texte_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_3.setText("0");
                        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        texte_chiffre_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

                        texte_chiffre_4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_chiffre_4.setText("0");
                        texte_chiffre_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        texte_chiffre_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(texte_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 30, -1));

                        down_chiffre_1.setText("\\/");
                        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_1ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

                        down_chiffre_2.setText("\\/");
                        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_2ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

                        down_chiffre_3.setText("\\/");
                        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_3ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

                        down_chiffre_4.setText("\\/");
                        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                down_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

                        bouton_tester.setText("Testez");
                        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_testerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

                        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts :");
                        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

                        texte_nb_chiffres_exacts.setText("0");
                        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 20, -1));

                        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts :");
                        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

                        texte_nb_chiffres__haut.setText("0");
                        getContentPane().add(texte_nb_chiffres__haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 10, -1));

                        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
                        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

                        texte_nb_chiffres_bas.setText("0");
                        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

                        texte_score.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
                        texte_score.setText("0 sur 5");
                        texte_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        texte_score.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 70));

                        texte_tentatives.setText("Tentatives");
                        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

                        bouton_recommencer.setText("Recommencer");
                        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bouton_recommencerActionPerformed(evt);
                            }
                        });
                        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
        int a = Solution .getVal_case1();
        texte_chiffre_1.setText(a + "");
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres__haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
